### ISSUE TITLE
Missing/incomplete instructions

### ISSUE THREAD

**Issue by leogansen** [pelias/docker#117]
Hi,

Your instructions for installing Pelias with Docker seem incomplete. After instruction to use command "pelias system env", the purpose of instructions that follow is not clear. How does one launch Pelias? What is the purpose of "Generic build workflow" section - hasn't Pelias been built by the time one reaches this point? And also, running any of the commands in this section generates feedback which looks like this:
++ update_terminal_cwd
++ local url_path=
++ local i ch hexch LC_CTYPE=C LC_ALL=
++ (( i = 0 ))
++ (( i < 51 ))
++ ch=/
++ [[ / =~ [/._~A-Za-z0-9-] ]]
...

And nothing happens. Please advise.
Leo

**Comment by orangejulius** [comment]
Hi @leogansen,
I think the structure of the README might have been unclear. The "Generic Build Workflow" section was indeed what you needed to follow.

I just pushed https://github.com/pelias/docker/commit/0724e435abc8bdef0d17db35a2b5bd1096106e97 to rearrange and clarify the README a bit. Let me know if it helps

**Comment by heidenthal** [comment]
I wrote a message on the other site indicating that there were issues with the documentation.  I wrote them there because I was searching for something more complete than here.  Julian, you asked that I write on this site as well.  I found this issue and decided it was similar to mine.

I will try again with the updated files and try again.  Do I need to uninstall anything before I start again?

**Comment by heidenthal** [comment]
When I tried to do this, of course, Docker failed.  So, I tried to do a complete installation.  As before, the documentation is obviously not written to be successful. I understand that open source doesn't mean one should actually be able to get a product which is commercial in any way to actually run locally.  Thanks for trying to create something that users could install.  

However, until someone unfamiliar with your product actually goes through the full installation instructions without help from anyone associated with it, then the instructions can't be considered viable.  At each step, I was redirected to other github instructions for pelias, so, here I am another 6 hours later with nothing working.

I really do appreciate your efforts, but at this point I have created an Upwork job to actually create useful, step-by-step instructions for installing Pelias.

**Comment by orangejulius** [comment]
@leogansen I'm really curious to hear if you were able to get things to work with the updated documentation. I can't for the life of me imagine what would cause that output, but hopefully starting from at least a clean terminal window should help.

@heidenthal Sorry you couldn't get things to work. We do work very hard to ensure that a project as complex as Pelias can be set up as easily as possible. Many people _are_ able to successfully set it up on their own, and we're always looking for ways to ensure that's the most common outcome. If you have any specific issues with things not working, we'd very much like to know about them in a new issue.

I'm going to close this issue since I think the core problem here was the confusing order of sections in the README, which has now been resolved. Again, feel free to open new issues for specific problems as they arise.
