### ISSUE TITLE
Pelias download geonames not working

### ISSUE THREAD

**Issue by umar18** [pelias/docker#131]
Hey team! 

"Pelias download geonames" does not work even import it returns error saying 
ERROR: geonames No Such Service.

Here is the pelias json file configuration

"geonames": {
      "datapath": "/data/geonames",
      "countryCode": "PK",
      "sourceURL":"https://download.geonames.org/export/dump/PK.zip"	
    }

**Comment by msschl** [comment]
I have the same problem...
```json
{
  "datapath": "/data/geonames",
  "countryCode": "DE"
}
```

**Comment by orangejulius** [comment]
Hey folks,

I think this happens because some of our projects are missing an entry in `docker-compose.yml` for Geonames. Geonames data is not relevant for all projects, especially smaller areas. Our default starting point, the Portland-metro area docker project, doesn't include Geonames for that reason.

If you don't need geonames data, feel free to skip `pelias download geonames` and `pelias import geonames`.

Otherwise you can copy the relevant section from one of the [projects that _do_ use Geonames](https://github.com/pelias/docker/blob/master/projects/planet/docker-compose.yml#L62-L69)

**Comment by msschl** [comment]
Thanks @orangejulius,
That fixed it for me.
