### ISSUE TITLE
Mac OS 10.15.4 

### ISSUE THREAD

**Issue by YoCuz** [pelias/docker#185]
Mac OS 10.15.4 [Catalina] install creates [Read Only File System] in the setup script path.
**Describe the bug**

mkdir /code /data path is now invalid due to [Read Only File System]
**Steps to Reproduce**

**Expected behavior**
commands execute
**Environment (please complete the following information):**

- OS: Mac OS 10.15.4 [Catlina]
 - Docker versions: Docker Desktop Client for Mac OS
**Pastebin/Screenshots**

<img width="566" alt="Screen Shot 2020-03-31 at 10 20 26 PM" src="https://user-images.githubusercontent.com/62674811/78092477-e9ee7500-739d-11ea-884e-78571aecd043.png">
**Additional context**

**Comment by missinglink** [comment]
You can substitute `/code` and `/data` for any paths on your system which are writable.

**Comment by orangejulius** [comment]
@missinglink, didn't you start seeing this a while back?

It sounds like we should update the readme to use different directories that are writeable by default. Most people seem to assume that they _must_ use `/code` and `/data`, so maybe we should find new defaults that aren't as problematic.

**Comment by missinglink** [comment]
I'm also running OSX and since Catalina it's no longer possible to create files/directories in the root of the filesystem.

Yeah I think my personal convention of `/data` and `/code` is confusing to first-time users.

I was actually thinking about this last night, anyway let's discuss a documentation fix outside of this bug report.
