### ISSUE TITLE
planet: Empty "extract.0sv"

### ISSUE THREAD

**Issue by divE4pip** [pelias/docker#198]
**Describe the bug**

I am getting an empty `pelias/data/polylines/extract.0sv` file after I run `pelias prepare polylines` on the planet build. 

I have the latest planet pbf file:
```
52G ../pelias/data/openstreetmap/planet-latest.osm.pbf
```

Any idea on what could be wrong?

Thanks

**Environment (please complete the following information):**
```
docker --version
Docker version 19.03.8, build afacb8b7f0

docker-compose --version
docker-compose version 1.25.0, build unknown
```

**Logs**

Logs of the `pelias prepare polylines` command:
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/data/openstreetmap/planet-latest.osm.pbf is very large.
You will likely experience memory issues working with large extracts like this.
We strongly recommend using Valhalla to produce extracts for large PBF extracts.
see: https://github.com/pelias/polylines#download!data
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
converting /data/openstreetmap/planet-latest.osm.pbf to /data/polylines/extract.0sv
```

**Comment by missinglink** [comment]
Thanks for the bug report, I suspect you are out of memory, see https://github.com/pelias/polylines/issues/245

You can download Valhalla extracts from [Geocode Earth](https://geocode.earth/data#openstreetmap).

**Comment by orangejulius** [comment]
This should be "fixed" by our recent change in https://github.com/pelias/polylines/pull/248. The `pelias prepare polylines` step will no longer even attempt to generate the polylines file when the file is too large to reasonably complete.

In the future we will probably integrate [Valhalla](https://github.com/valhalla/valhalla) directly into the Docker build process (see the initial steps in https://github.com/pelias/docker-valhalla-baseimage) so that anyone can run this prepare step on their own without additional setup.

For now, running Valhalla locally can be done with a bit of manual work, and of course the Geocode Earth downloads are [still available](https://geocode.earth/data#openstreetmap).
