### ISSUE TITLE
Scale up feature for docker

### ISSUE THREAD

**Issue by scepeda78** [pelias/docker#229]
### Use-cases

To scale up the service to simultaneous execution of the docker compose

### Attempted Solutions

it dint work with the command line scale nor with a load balancer in nginx

https://pspdfkit.com/blog/2018/how-to-use-docker-compose-to-run-multiple-instances-of-a-service-in-development/

### Proposal

Elastic search was the one causing problems, after the scale has been done on the api

**Comment by missinglink** [comment]
Hi @scepeda78 

Sorry for the slow reply on this one, the topic is a bit out-of-scope for the `docker-compose` workflow which is why you didn't get much response.

The `docker-compose` workflow is only supported in development. We run the exact same docker images in production using [kubernetes](https://github.com/pelias/kubernetes) for orchestration.

As you discovered, having everything "just scale out horizontally" is not as easy as it sounds, we would not likely consider supporting that in the docker-compose setup due to the complexity.

**Comment by missinglink** [comment]
For more info about how elasticsearch scales, check out this guide:
https://logz.io/blog/elasticsearch-cluster-tutorial/
