### ISSUE TITLE
Throw error if pelias.json is not configured correctly

### ISSUE THREAD

**Issue by arnesetzer** [pelias/docker#291]
### Use-cases

After searching for an error due to my polylines for 3 days I finally recognized that I accidently typed
 `"polylines": {
      "datapath": "/data/polylines",
      "files":["extract.0sv"]
    }`
instead of `"polyline":{...`
which let the polyline service running idle a few times over hours without any time of feedback.
### Attempted Solutions

It would be nice if the called micro service couldnt find any configuration nor import file to show an error like "missing/wrong configuration, please check your pelias.json" instead of running idle. 

### Proposal

It would (also) may be a workaround solution to rename/also accept "polyline**s**" as configuration name for the polylines since the repository is called with an s and the pelias command is also called with an s, so it's very confusing that the configuration is written without an s.

### References

Found nothing.

PS: Hope this belongs here and it's understandable what I tried to explain

**Comment by orangejulius** [comment]
Hi @arnesetzer,
Yes, this has unfortunately been an issue since [the beginning](https://github.com/pelias/polylines/issues/4).

Due to the way JSON configurations work (there is a default config defined in the `pelias-config` module), we probably can't accept _both_ `polylines` and `polyline`.

However, we could detect if there is a `polylines` property defined and throw a fatal error to at least save people like yourselves some time.

**Comment by arnesetzer** [comment]
Ah, I see. That has been an older issue 🙈
The workaround looks like the easiest solution to approch this problem without rewriting a lot of the `pelias-config` module or killing leagcy support.

Thanks for your reply
