### ISSUE TITLE
connect ECONNREFUSED ip:4400

### ISSUE THREAD

**Issue by arungowtham** [pelias/docker#47]
Hi Team,

I tried making this query :  `http://localhost:4000/v1/search?text=LL11 6QA`

1.  With api, libpostal and elasticsearch service running : I get _connect ECONNREFUSED 172.18.0.2:4400_ error.

          {"geocoding":{"version":"0.2","attribution":"http://localhost:4000/attribution","query":{"text":"LL11 6QA","size":10,"private":false,"focus.point.lat":45.52,"focus.point.lon":-122.67,"lang":{"name":"English","iso6391":"en","iso6393":"eng","defaulted":false},"querySize":20},"errors":["connect ECONNREFUSED 172.18.0.2:4400"],"engine":{"name":"Pelias","author":"Mapzen","version":"1.0"},"timestamp":1542550520313},"type":"FeatureCollection","features":[]}

- When i kill elasticsearch service that error isn't thrown and the query is parsed by libpostal.

          {"geocoding":{"version":"0.2","attribution":"http://localhost:4000/attribution","query":{"text":"LL11 6QA","size":10,"private":false,"focus.point.lat":45.52,"focus.point.lon":-122.67,"lang":{"name":"English","iso6391":"en","iso6393":"eng","defaulted":false},"querySize":20,"parser":"libpostal","parsed_text":{"postalcode":"ll11 6qa"}},"errors":["No Living connections"],"engine":{"name":"Pelias","author":"Mapzen","version":"1.0"},"timestamp":1542550596264},"type":"FeatureCollection","features":[]}

2. After killing elasticsearch service i alter the query by removing the space in it, now the parser falls back to addressit, is this intentional ?

          {"geocoding":{"version":"0.2","attribution":"http://localhost:4000/attribution","query":{"text":"LL116QA","size":10,"private":false,"focus.point.lat":45.52,"focus.point.lon":-122.67,"lang":{"name":"English","iso6391":"en","iso6393":"eng","defaulted":false},"querySize":20,"parser":"addressit","parsed_text":{}},"errors":["No Living connections"],"engine":{"name":"Pelias","author":"Mapzen","version":"1.0"},"timestamp":1542550613545},"type":"FeatureCollection","features":[]}

**Comment by orangejulius** [comment]
Hey @arungowtham,
This is an interesting report, thanks. Querying libpostal is the very first thing the search endpoint does, so I suspect it's not actually elasticsearch being up or not that's causing the ECONREFUSED error. At least I hope not, and if so it would definitely represent a bug...somewhere.

What I _suspect_ is the cause is that the libpostal service can sometimes take a few seconds (maybe even 30 or so) to start up. It does have to load about 2GB of data into memory after all.

Can you confirm that even if the libpostal service has been up and working for a few minutes, you can replicate this behavior by starting/stopping Elasticsearch? If so, can you also share a few more details of your setup? Looks like you're using a docker project, so `pelias.json` and `docker-compose.yml` is a good place to start.

Thanks!

**Comment by arungowtham** [comment]
Hi @orangejulius ,

Yes, seems elasticsearch isn't causing those errors, weird alteast libpostal worked and parsed yesterday when i brought down elasticsearch.

I get two errors : 

When `docker ps` lists

<img width="1324" alt="screen shot 2018-11-19 at 12 34 11 pm" src="https://user-images.githubusercontent.com/19775829/48691152-79571600-ebf7-11e8-8717-6050c2f7a157.png">

I receive :  "errors":["connect ECONNREFUSED 172.18.0.2:4400"]

When `docker ps` lists

<img width="1420" alt="screen shot 2018-11-19 at 12 35 18 pm" src="https://user-images.githubusercontent.com/19775829/48691189-9db2f280-ebf7-11e8-9c19-848dfd9db318.png">

I receive :  "errors":["getaddrinfo ENOTFOUND libpostal libpostal:4400"]


The second case happens automatically, not sure why it went to restarting state.

Is there a way/API to send requests to docker libpostal service and see if it's working, that ip 172.18.0.2 is virtual, specific to the docker container, so not able to access from my machine browser.

**Comment by orangejulius** [comment]
Are you using OSX? How much RAM did you allocate to Docker if so, and how much free RAM does your system have if not? The libpostal service is pretty memory heavy, so I suspect similar to https://github.com/pelias/docker/issues/41#issuecomment-438344570 it might not be getting enough here.

**Comment by arungowtham** [comment]
Yes that's the issue, default RAM was set to 2GB and 4 cores, bumped it to 8GB, now queries are parsed by either libpostal/addressit. Thanks @orangejulius 

Could be added in the https://github.com/pelias/docker#prerequisites section !

----

I have another doubt : 

Is it possible to point the docker services(api, interpolation, libpostal) to a running elasticsearch cluster instead of your pelias-elasticsearch docker service ? Should it be mentioned in pelias.json ? i.e use docker services to download, import, search, using existing es clusters.

**Comment by orangejulius** [comment]
Hah funny, it is already in the prerequisite settings (we might need to make it more clear).

Yes, by updating `pelias.json` you can use a separate Elasticsearch cluster just fine.

**Comment by arungowtham** [comment]
My bad ..

**Comment by I1mran** [comment]
I am facing the same issue.

![image](https://user-images.githubusercontent.com/32770021/70730099-2ed69900-1d26-11ea-905a-91483b5c38c4.png)

 libpostal-service is working fine with..
127.0.0.1:4400/expand?address=portland
```["portland"]```
127.0.0.1:4400/parse?address=portland
```[{"label": "city", "value": "portland"}]```

**Comment by missinglink** [comment]
If the service is running then it could be a hostname issue or a networking issue.

Try entering an interactive shell within the container which is having the error using `docker exec {container} bash` (or some variant of that command) and then issue a `curl` request using the hostname defined in your pelias.json config

**Comment by missinglink** [comment]
Networking issues can be caused by changing any of the networking settings in `docker-compose.yml` or the hostnames in pelias.json, either of those things will likely break everything.

If the hostnames are correct you can try bringing everything `down` then `up`, I have found in the past that launching a compose project and then later adding additional services meant that the original services couldn't see the new ones until after they were recreated.

**Comment by I1mran** [comment]
in my case, it was an issue with placeholder service. it was not working properly.
